apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        env:
        - name: SQL_USER
          value: username
        - name: SQL_PASSWD
          value: password
        - name: SQL_DB
          value: wordpress

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - name: sql
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
