apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: INFLUX_HOST
          value: influxdb-service 
        - name: SQL_HOST
          value: mysql-service
        - name: SQL_DB
          value: ft_services
        - name: SQL_USER
          value: username
        - name: SQL_PASSWD
          value: password

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
